### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by Leftorius** [nflantier/SFA2.0-1.10.2#2]
http://pastebin.com/WdTKrePb

if I try to open the Liquefier, the game crashes.

EDIT: doesn't matter what, every machine with an gui does crash as soon as I try to open it.

**Comment by nflantier** [comment]
every machine of every mods or only those from sfartifacts?

**Comment by Leftorius** [comment]
only those from sfartifacts

**Comment by nflantier** [comment]
ok i uploaded a probable fix [2.0.1](https://minecraft.curseforge.com/projects/sfartifacts/files)

**Comment by Leftorius** [comment]
I'll test it :D Thanks

**Comment by Leftorius** [comment]
it's fixed! Thanks man :)
